apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: backend
data:
  APP_NAME: "Multi-Cloud Backend"
  APP_ENV: "production"
  LOG_LEVEL: "INFO"
  AWS_REGION: "eu-central-1"
  S3_CONFIG_KEY: "config.json"